config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new create show]
  resources :events, only: %i[index new create show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
  validates :description, presence: true
  validates :date, presence: true

  belongs_to :creator, class_name: 'User'
  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees, source: :attendee

  scope :upcoming_scope, -> { where('date >= ?', DateTime.now.to_date) }
  scope :previous_scope, -> { where('date < ?', DateTime.now.to_date) }

  def self.upcoming
    Event.upcoming_scope
  end

  def self.previous
    Event.previous_scope
  end
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :event_attendees, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendees, source: :attended_event

  validates :username, presence: true, length: { in: 3..20 },
                       uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 244 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  def upcoming_events
    events.where('date >=?', DateTime.now)
  end

  def previous_events
    events.where('date <=?', DateTime.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def home; end

  private

  # Before filters

  # Confirms and filters a logged-in user.
  def logged_in_user
    if logged_in?
      redirect_to(user_path(@current_user)) if params[:id] != @current_user.id.to_s
    else
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to events_path(@event)
    else
      render :new
    end
  end

  def index
    @events = Event.all
    @previous_events = Event.previous
    @upcoming_events = Event.upcoming
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email])

    if user
      log_in user
      flash[:notice] = 'Login successfully'
      redirect_to user_path(user)
    else
      flash.now[:notice] = 'Email does not exist'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.upcoming_events
    @previous_events = @user.previous_events
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Events</h1>

<h2>List of Upcoming Events</h2>
<div>
  <% @upcoming_events.each do |event| %>

  <p>
   <strong>Event:</strong><%= event.name %>
   </p>

    <p>
    <strong>Location:</strong><%= event.location %>
    </p>

    <p>
    <strong>Description:</strong><%= event.description %>
    </p>

    <p>
    <strong>Date:</strong><%= event.date %>
    </p>
  <% end %>
</div>

<h2>List of Past Events</h2>
<div>
  <% @previous_events.each do |event| %>

  <p>
   <strong>Event:</strong><%= event.name %>
   </p>

    <p>
    <strong>Location:</strong><%= event.location %>
    </p>

    <p>
    <strong>Description:</strong><%= event.description %>
    </p>

    <p>
    <strong>Date:</strong><%= event.date %>
    </p>
  <% end %>
</div>

app/views/events/new.html.erb
<h1 align="center">Create A New Event</h1>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(:event,  :html => {class: "form-horizontal", role: "form"}, :url => events_path) do |f| %>
      <div class="form-group ">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", autofocus: true %>
        </div>
      </div>
      <div class="form-group ">
        <div class="control-label col-sm-2">
          <%= f.label :location %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :location, class: "form-control" %>
        </div>
      </div>
      <div class="form-group ">
        <div class="control-label col-sm-2">
          <%= f.label :date %>
        </div>
        <div class="col-sm-8">
          <%= f.date_field :date, class: "form-control" %>
        </div>
      </div>
      <div class="form-group ">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control" %>
        </div>
      </div>
      <div class="form-group ">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Create Event', class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<h2> Created by:<%= @event.creator.username %></h2>

<% @event.attendees.each do |attendee| %>
  <%= attendee.name %><br />
<%end%>

<%= link_to 'My Events', user_path(@event)  %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">

<div class="container-fluid">

<!-- Brand and toggle get grouped for better mobile display -->

<div class="navbar-header">

<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

<span class="sr-only">Toggle navigation</span>

<span class="icon-bar"></span>

<span class="icon-bar"></span>

<span class="icon-bar"></span>

</button>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
    <li><%= link_to 'All Events', events_path %></li>
    <li><%= link_to 'Create Event', new_event_path  %></li>
  </ul>

  <ul class="nav navbar-nav navbar-right">
  <% if logged_in?  %>
    <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
    <% else %>
    <li><%= link_to 'Sign Up', new_user_path %></li>
    <% end %>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= flash[:alert] %>
  <%= flash[:notice] %>

    <%= render 'layouts/navigation' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1 align="center">Create a User</h1>

<div class="row">
  <div class="col-xs-12">

    <%= form_for (@user), :html => {class: "form-horizontal", role: "form"}, :url => users_path do |f| %>
      <div class="form-group ">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group ">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>

      <div class="form-group ">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Create User", class: 'btn btn-primary btn-lg'%>
          </div>
      </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">
  Welcome <%= @user.username %>
</h1>

<h2>List of Upcoming Events</h2>
<div>
  <% @upcoming_events.each do |event| %>

  <p>
   <strong>Event:</strong><%= event.name %>
   </p>

    <p>
    <strong>Location:</strong><%= event.location %>
    </p>

    <p>
    <strong>Description:</strong><%= event.description %>
    </p>

    <p>
    <strong>Date:</strong><%= event.date %>
    </p>
  <% end %>
</div>

<h2>List of Past Events</h2>
<div>
  <% @previous_events.each do |event| %>

  <p>
   <strong>Event:</strong><%= event.name %>
   </p>

    <p>
    <strong>Location:</strong><%= event.location %>
    </p>

    <p>
    <strong>Description:</strong><%= event.description %>
    </p>

    <p>
    <strong>Date:</strong><%= event.date %>
    </p>
  <% end %>
</div>